version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '80:80'
    environment:
      - VITE_API_URL=http://backend:3001
      - VITE_TELEGRAM_TOKEN=${VITE_TELEGRAM_TOKEN}
    depends_on:
      - backend
    networks:
      - supermock-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_USERNAME=SuperMock_bot
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://frontend:80
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - postgres
    networks:
      - supermock-network

  postgres:
    image: postgres:15-alpine
    container_name: supermock-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-supermock}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - supermock-network

volumes:
  postgres_data:
    driver: local

networks:
  supermock-network:
    driver: bridge
