version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_URL=http://backend:3001
      - VITE_TELEGRAM_TOKEN=${VITE_TELEGRAM_TOKEN}
    depends_on:
      - backend
    networks:
      - supermock-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`supermock.ru`) && PathPrefix(`/`)'
      - 'traefik.http.routers.frontend.entrypoints=http'
      - 'traefik.http.routers.frontend.entrypoints=https'
      - 'traefik.http.routers.frontend.tls.certresolver=letsencrypt'
      - 'traefik.http.services.frontend.loadbalancer.server.port=80'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    # Убираем внешние порты - Traefik будет проксировать
    # ports:
    #   - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_USERNAME=SuperMock_bot
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://frontend:80
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - supermock-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:3001/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`supermock.ru`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.backend.entrypoints=http'
      - 'traefik.http.routers.backend.entrypoints=https'
      - 'traefik.http.routers.backend.tls.certresolver=letsencrypt'
      - 'traefik.http.services.backend.loadbalancer.server.port=3001'
      - 'traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api'
      - 'traefik.http.routers.backend.middlewares=backend-stripprefix'

  postgres:
    image: postgres:15-alpine
    container_name: supermock-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-supermock}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    # Убираем внешние порты - только внутренний доступ
    # ports:
    #   - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - supermock-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  supermock-network:
    driver: bridge
