services:
  # База данных PostgreSQL для разработки
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supermock
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - supermock-network

  # Бэкенд для разработки
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3002:3001'
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/supermock
      - JWT_SECRET=dev-secret-key-change-in-production
      - JWT_EXPIRES_IN=7d
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-}
      - BOT_USERNAME=${BOT_USERNAME:-}
      - FRONTEND_URL=http://localhost:5174
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - supermock-network
    depends_on:
      - postgres
    command: npm run dev

  # Фронтенд для разработки
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '5174:5173'
    environment:
      - VITE_API_URL=http://localhost:3002
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - supermock-network
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:

networks:
  supermock-network:
    driver: bridge
