version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://api.supermock.ru
        - VITE_TELEGRAM_BOT_USERNAME=SuperMock_bot
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    expose:
      - 80
    networks:
      - dokploy-network
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.supermock-frontend.rule=Host(`supermock.ru`)
      - traefik.http.routers.supermock-frontend.entrypoints=websecure
      - traefik.http.routers.supermock-frontend.tls.certResolver=letsencrypt
      - traefik.http.services.supermock-frontend.loadbalancer.server.port=80

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    expose:
      - 3001
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:krishna1284radha@database:5432/supermock?schema=public
      - JWT_SECRET=052aa937e5faf8542efe8c091a7ff830
      - JWT_EXPIRES_IN=7d
      - TELEGRAM_TOKEN=8464088869:AAFcZb7HmYQJa6vaYjfTDCjfr187p9hhk2o
      - BOT_USERNAME=SuperMock_bot
      - FRONTEND_URL=https://supermock.ru
      - BACKEND_URL=https://api.supermock.ru
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    networks:
      - dokploy-network
    volumes:
      - ../files/backend-logs:/app/logs
    labels:
      - traefik.enable=true
      - traefik.http.routers.supermock-backend.rule=Host(`api.supermock.ru`)
      - traefik.http.routers.supermock-backend.entrypoints=websecure
      - traefik.http.routers.supermock-backend.tls.certResolver=letsencrypt
      - traefik.http.services.supermock-backend.loadbalancer.server.port=3001

  database:
    image: postgres:16-alpine
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: krishna1284radha
      POSTGRES_DB: supermock
    networks:
      - dokploy-network
    volumes:
      - ../files/postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d supermock
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  dokploy-network:
    external: true
