name: Deploy to Dokploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Dokploy
        uses: dokploy/dokploy-action@v1
        with:
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
          dokploy_token: ${{ secrets.DOKPLOY_TOKEN }}
          application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
